const fileUploaderConfig = {
  allowMultiple: true,
  maxFiles: 1000,
  checkValidity: true,
  allowFilePoster: true,
  allowFileSizeValidation: true,
  maxFileSize: '1MB',
  labelMaxFileSizeExceeded: 'حجم فایل زیاد است',
  labelMaxFileSize: 'حداکثر حجم مجاز: {filesize}',
  filePosterMinHeight: 100,
  filePosterMaxHeight: 300,
  allowImagePreview: true,
  imagePreviewMaxHeight: 300,
  allowImageValidateSize: true,
  imageValidateSizeLabelFormatError: 'نوع عکس مجاز نیست',
  imageValidateSizeLabelImageSizeTooSmall: 'عکس بسیار کوچک است',
  imageValidateSizeLabelImageSizeTooBig: 'عکس بسیار بزرگ است',
  imageValidateSizeLabelExpectedMinSize:
    'حداقل سایز عکس: {minWidth} × {minHeight}',
  imageValidateSizeLabelExpectedMaxSize:
    'حداکثر سایز عکس: {maxWidth} × {maxHeight}',
  allowFileTypeValidation: true,
  acceptedFileTypes: ['image/png', 'image/jpg', 'image/jpeg'],
  labelFileTypeNotAllowed: 'فایل انتخابی مجاز نیست',
  server: {
    url: 'https://dl.iranhostserver.ir/Uploader',
    process: '/Process',
    // revert: {
    //   url: '/Revert',
    //   method: 'POST',
    // },
  },
  labelIdle: 'عکس را اینجا رها یا کلیک کنید',
  labelInvalidField: 'فایل معنبر نیست',
  labelFileProcessing: 'درحال بارگذاری',
  labelFileProcessingError: 'خطا در بارگذاری',
  labelFileLoading: 'درحال بارگیری',
  labelFileLoadError: 'خطا در بارگیری',
  labelFileProcessingComplete: 'بارگذاری موفق',
  labelFileProcessingAborted: 'لغو بارگذاری',
  labelFileProcessingRevertError: 'خطا در بازگشتن',
  labelFileRemoveError: 'خطا در حذف',
  labelTapToCancel: 'لغو',
  labelTapToRetry: 'تلاش مجدد',
  labelTapToUndo: 'بازگردانی',
  labelButtonRemoveItem: 'حذف',
  labelButtonRetryItemLoad: 'تلاش مجدد',
  labelButtonAbortItemProcessing: 'لغو',
  labelButtonUndoItemProcessing: 'بازنشانی',
  labelButtonRetryItemProcessing: 'تلاش مجدد',
  labelButtonProcessItem: 'بارگذاری',
};

export default fileUploaderConfig;
