const dataGridLocalText = {
  toolbarDensity: 'سایز',
  toolbarDensityCompact: 'کوچک',
  toolbarDensityStandard: 'معمولی',
  toolbarDensityComfortable: 'بزرگ',
  toolbarFilters: 'فیلتر',
  toolbarColumns: 'ستون ها',
  filterPanelInputPlaceholder: 'جست و جو',
  filterPanelInputLabel: 'نام',
  filterPanelOperators: 'تشابه',
  filterOperatorContains: 'شامل شدن',
  filterOperatorEquals: 'برابر بودن',
  filterOperatorStartsWith: 'شروع با',
  filterOperatorEndsWith: 'اتمام با',
  filterOperatorIsEmpty: 'خالی بودن',
  filterOperatorIsNotEmpty: 'خالی نبودن',
  filterOperatorIsAnyOf: 'هرکدام',
  filterPanelColumns: 'ستون ها',
  checkboxSelectionHeaderName: 'چک باکس ها',
  columnsPanelShowAllButton: 'نمایش همه',
  columnsPanelHideAllButton: 'پنهان کردن همه',
  columnsPanelTextFieldLabel: 'پیدا کردن ستون',
  columnsPanelTextFieldPlaceholder: 'اسم ستون',
};

export default dataGridLocalText;
